######################Download data in R ###########################
library(readr)
Logit_Simmons_data <- read_csv("C:/GLIM/PM/Group Assignment/Logit-Simmons.csv")
######################Data Analysis#################################
Sim_data <- data.frame(Logit_Simmons_data)
head(Sim_data)
str(Sim_data)

## check missing values
sapply(Sim_data,function(x) sum(is.na(x)))
# found none

## more data Insights
library(MASS)
sapply(Sim_data,sd)

##################### Build the Logistic Model #####################
## We are not considering Customer variable as it is unnecessary
## Taking all the variables
logit_S=glm(Purchase~Spending+Card, data=Sim_data, family=binomial) 
## Taking only Spending
logit_S1=glm(Purchase~Spending, data=Sim_data, family=binomial) 
## Taking only Cards
logit_S2=glm(Purchase~Card, data=Sim_data, family=binomial) 

## Check the model parameters 
summary(logit_S) 
# The Spending and Card parameters looks statistically significant.
# A unit increase for customers with Card increases the log odds by 1.1 
# while same 1 unit increase in spending increases the log odds by 0.34

## Run the anova() function on the model to analyze the table of deviance 
anova(logit_S, test = "Chisq")
# There is a drop in deviance of around 1 unit by adding card to spending.
# The model seems to be doing good compared to null model (Look into NULL deviance)
# Check the McFadden R2 index equivalent to R2 for linear regression to access model fit.
library(pscl)
pR2(logit_S)
#
# CIs using profiled log-likelihood :: confint function to obtain confidence
# intervals ofcoefficient estimates
confint(logit_S) 

# CI using standard errors
confint.default(logit_S)

#Exponentiate the coefficients to interpret the results as odds-ratios
# odds ratios
exp(coef(logit_S)) 

# Odds ratios and 95% CI
exp(cbind(OR = coef(logit_S), confint(logit_S))) 

##################Calculate the predicted probability and accuracy ##########
# We aded a new variable PredPurchase to original dataset to see how our model is predicting.
# Note that Type = response tells R to calculate predicted probability
Sim_data$PredPurchase <- predict(logit_S, type='response') 
head(Sim_data$PredPurchase)
Sim_data$PredPurchase <- ifelse(Sim_data$PredPurchase > 0.5,1,0)
misClassificationError <- mean(Sim_data$PredPurchase != Sim_data$Purchase)
print(paste('Accuracy of Model is : ', 1 - misClassificationError))

################### Test the Model accuracy ##############################
## calculate the P-value of our models.
#with(logit_S, pchisq(null.deviance - deviance, df.null - df.residual, lower.tail = FALSE))
#with(logit_S1, pchisq(null.deviance - deviance, df.null - df.residual, lower.tail = FALSE))
#with(logit_S2, pchisq(null.deviance - deviance, df.null - df.residual, lower.tail = FALSE))

## Calculate chi-sq 
#with(logit_S, null.deviance - deviance)
#with(logit_S1, null.deviance - deviance)
#with(logit_S2, null.deviance - deviance)
##
## Check the measures to see how well our model fits using Likelihood ratio test.
library(lmtest) 
lrtest(logit_S) 
lrtest(logit_S1) 
lrtest(logit_S2) 
# Compare the Log likelihood
Compare_models_logLik <- cbind(logLik(logit_S), logLik(logit_S1), logLik(logit_S2))
Compare_models_logLik

# We will go with Model1, that is logit_S which has high Chi- sq value of 13.63 
# 3 degress of freedom and P-value of 0.0011 and fits better than other 2 models.
################### Visualize the Model performance ############33####################
# Let us plot the ROC curve and calculate the AUC for performance measurements
# Note : The Roc is curve generated by plotting the true positive rate(TPR) against the false 
# positive rate (FPR) at various threshold settings while the AUC is the area under the ROC curve.
# A model with good predictive ability should have AUC close to 1 (ideal)
library(ROCR)
perf <- prediction(Sim_data$PredPurchase, Sim_data$Purchase)
PerfMeas <- performance(perf, measure = "tpr", x.measure = "fpr")
plot(PerfMeas)

AUC <- performance(perf, measure = "auc") 
AUC <- AUC@y.values[[1]]
print(paste('Area Under the Curve of Model is : ', AUC))

#### The model has an accuracy of 72 % and area nder the curve is around 68%.
#### Clearly, this is an average model. May be we can get better prediction 
#### by having larger dataset or adding more parameters. FPR is definitely high.

#########################Answer questions based on Insights from case study ##################
## Odds for customer having card who spent 200$
Simon21=data.frame(Spending=2, Card=1) 
PredProb21=predict(logit_S, Simon21, type='response') 
PredProb21
Odds21=PredProb21/(1-PredProb21) 
Odds21 
## Odds for customer not having card but spent 200$
Simon20=data.frame(Spending=2, Card=0) 
PredProb20=predict(logit_S, Simon20, type='response') 
PredProb20 
Odds20=PredProb20/(1-PredProb20) 
Odds20 
## Odds Ratio 
Odds=Odds21/Odds20 
Odds

